/* tslint:disable */
/* eslint-disable */
/**
 * Compliance Framework Configuration Service API
 * This is the API for the Compliance Framework Configuration Service.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DomainLink } from './domain-link';
import { DomainPart } from './domain-part';
import { DomainProperty } from './domain-property';
/**
 * 
 * @export
 * @interface DomainPart
 */
export interface DomainPart {
    /**
     * An optional textual providing a sub-type or characterization of the part's name, or a category to which the part belongs.
     * @type {string}
     * @memberof DomainPart
     */
    _class?: string;
    /**
     * A unique identifier for the part.
     * @type {string}
     * @memberof DomainPart
     */
    id?: string;
    /**
     * 
     * @type {Array<DomainLink>}
     * @memberof DomainPart
     */
    links?: Array<DomainLink>;
    /**
     * A textual label that uniquely identifies the part's semantic type, which exists in a value space qualified by the ns.
     * @type {string}
     * @memberof DomainPart
     */
    name?: string;
    /**
     * An optional namespace qualifying the part's name. This allows different organizations to associate distinct semantics with the same name.
     * @type {string}
     * @memberof DomainPart
     */
    ns?: string;
    /**
     * 
     * @type {Array<DomainPart>}
     * @memberof DomainPart
     */
    parts?: Array<DomainPart>;
    /**
     * 
     * @type {Array<DomainProperty>}
     * @memberof DomainPart
     */
    props?: Array<DomainProperty>;
    /**
     * Permits multiple paragraphs, lists, tables etc.
     * @type {string}
     * @memberof DomainPart
     */
    prose?: string;
    /**
     * An optional name given to the part, which may be used by a tool for display and navigation.
     * @type {string}
     * @memberof DomainPart
     */
    title?: string;
}
