/* tslint:disable */
/* eslint-disable */
/**
 * Compliance Framework Configuration Service API
 * This is the API for the Compliance Framework Configuration Service.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DomainLink } from "./domain-link";
import { DomainObjectiveSelection } from "./domain-objective-selection";
import { DomainProperty } from "./domain-property";
import { DomainSelection } from "./domain-selection";
/**
 *
 * @export
 * @interface DomainControlsAndObjectives
 */
export interface DomainControlsAndObjectives {
  /**
   *
   * @type {DomainSelection}
   * @memberof DomainControlsAndObjectives
   */
  controlSelections?: DomainSelection;
  /**
   *
   * @type {string}
   * @memberof DomainControlsAndObjectives
   */
  description?: string;
  /**
   *
   * @type {Array<DomainLink>}
   * @memberof DomainControlsAndObjectives
   */
  links?: Array<DomainLink>;
  /**
   *
   * @type {Array<DomainObjectiveSelection>}
   * @memberof DomainControlsAndObjectives
   */
  objectives?: Array<DomainObjectiveSelection>;
  /**
   *
   * @type {Array<DomainProperty>}
   * @memberof DomainControlsAndObjectives
   */
  props?: Array<DomainProperty>;
  /**
   *
   * @type {string}
   * @memberof DomainControlsAndObjectives
   */
  remarks?: string;
  /**
   *
   * @type {string}
   * @memberof DomainControlsAndObjectives
   */
  title?: string;
}
