/* tslint:disable */
/* eslint-disable */
/**
 * Compliance Framework Configuration Service API
 * This is the API for the Compliance Framework Configuration Service.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DomainLink } from "./domain-link";
import { DomainPart } from "./domain-part";
import { DomainProperty } from "./domain-property";
/**
 *
 * @export
 * @interface DomainObjective
 */
export interface DomainObjective {
  /**
   *
   * @type {string}
   * @memberof DomainObjective
   */
  control?: string;
  /**
   *
   * @type {string}
   * @memberof DomainObjective
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof DomainObjective
   */
  id?: string;
  /**
   *
   * @type {Array<DomainLink>}
   * @memberof DomainObjective
   */
  links?: Array<DomainLink>;
  /**
   *
   * @type {Array<DomainPart>}
   * @memberof DomainObjective
   */
  parts?: Array<DomainPart>;
  /**
   *
   * @type {Array<DomainProperty>}
   * @memberof DomainObjective
   */
  props?: Array<DomainProperty>;
  /**
   *
   * @type {string}
   * @memberof DomainObjective
   */
  remarks?: string;
  /**
   *
   * @type {string}
   * @memberof DomainObjective
   */
  title?: string;
}
