/* tslint:disable */
/* eslint-disable */
/**
 * Compliance Framework Configuration Service API
 * This is the API for the Compliance Framework Configuration Service.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DomainLink } from './domain-link';
import { DomainProperty } from './domain-property';
/**
 * 
 * @export
 * @interface DomainFacet
 */
export interface DomainFacet {
    /**
     * 
     * @type {string}
     * @memberof DomainFacet
     */
    description?: string;
    /**
     * 
     * @type {Array<DomainLink>}
     * @memberof DomainFacet
     */
    links?: Array<DomainLink>;
    /**
     * 
     * @type {string}
     * @memberof DomainFacet
     */
    name?: string;
    /**
     * 
     * @type {Array<DomainProperty>}
     * @memberof DomainFacet
     */
    props?: Array<DomainProperty>;
    /**
     * 
     * @type {string}
     * @memberof DomainFacet
     */
    remarks?: string;
    /**
     * One of: http://fedramp.gov, http://fedramp.gov/ns/oscal, http://csrc.nist.gov/ns/oscal, http://csrc.nist.gov/ns/oscal/unknown, http://cve.mitre.org, http://www.first.org/cvss/v2.0, http://www.first.org/cvss/v3.0, http://www.first.org/cvss/v3.1
     * @type {string}
     * @memberof DomainFacet
     */
    system?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainFacet
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainFacet
     */
    value?: string;
}
