/* tslint:disable */
/* eslint-disable */
/**
 * Compliance Framework Configuration Service API
 * This is the API for the Compliance Framework Configuration Service.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DomainOrigin
 */
export interface DomainOrigin {
    /**
     * 
     * @type {Array<string>}
     * @memberof DomainOrigin
     */
    actors?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DomainOrigin
     */
    relatedTasks?: Array<string>;
}
