/* tslint:disable */
/* eslint-disable */
/**
 * Compliance Framework Configuration Service API
 * This is the API for the Compliance Framework Configuration Service.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DomainEvidence } from './domain-evidence';
import { DomainLink } from './domain-link';
import { DomainProperty } from './domain-property';
/**
 * 
 * @export
 * @interface DomainObservation
 */
export interface DomainObservation {
    /**
     * 
     * @type {string}
     * @memberof DomainObservation
     */
    collected?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainObservation
     */
    description?: string;
    /**
     * 
     * @type {Array<DomainEvidence>}
     * @memberof DomainObservation
     */
    evidences?: Array<DomainEvidence>;
    /**
     * 
     * @type {string}
     * @memberof DomainObservation
     */
    expires?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainObservation
     */
    id?: string;
    /**
     * 
     * @type {Array<DomainLink>}
     * @memberof DomainObservation
     */
    links?: Array<DomainLink>;
    /**
     * 
     * @type {Array<DomainProperty>}
     * @memberof DomainObservation
     */
    props?: Array<DomainProperty>;
    /**
     * 
     * @type {string}
     * @memberof DomainObservation
     */
    remarks?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainObservation
     */
    title?: string;
}
