/* tslint:disable */
/* eslint-disable */
/**
 * Compliance Framework Configuration Service API
 * This is the API for the Compliance Framework Configuration Service.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DomainFacet } from "./domain-facet";
import { DomainLink } from "./domain-link";
import { DomainOrigin } from "./domain-origin";
import { DomainProperty } from "./domain-property";
/**
 *
 * @export
 * @interface DomainCharacterization
 */
export interface DomainCharacterization {
  /**
   *
   * @type {Array<DomainFacet>}
   * @memberof DomainCharacterization
   */
  facets?: Array<DomainFacet>;
  /**
   *
   * @type {Array<DomainLink>}
   * @memberof DomainCharacterization
   */
  links?: Array<DomainLink>;
  /**
   *
   * @type {DomainOrigin}
   * @memberof DomainCharacterization
   */
  origin?: DomainOrigin;
  /**
   *
   * @type {Array<DomainProperty>}
   * @memberof DomainCharacterization
   */
  props?: Array<DomainProperty>;
}
