/* tslint:disable */
/* eslint-disable */
/**
 * Compliance Framework Configuration Service API
 * This is the API for the Compliance Framework Configuration Service.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DomainPart } from './domain-part';
/**
 * 
 * @export
 * @interface DomainAttestation
 */
export interface DomainAttestation {
    /**
     * 
     * @type {Array<DomainPart>}
     * @memberof DomainAttestation
     */
    parts?: Array<DomainPart>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DomainAttestation
     */
    responsibleParties?: Array<string>;
}
