/* tslint:disable */
/* eslint-disable */
/**
 * Compliance Framework Configuration Service API
 * This is the API for the Compliance Framework Configuration Service.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DomainObjective } from "./domain-objective";
/**
 *
 * @export
 * @interface DomainLocalDefinition
 */
export interface DomainLocalDefinition {
  /**
   * Reference to Activity
   * @type {Array<string>}
   * @memberof DomainLocalDefinition
   */
  activities?: Array<string>;
  /**
   * Reference to component.Component
   * @type {Array<string>}
   * @memberof DomainLocalDefinition
   */
  components?: Array<string>;
  /**
   * Reference to ssp.InventoryItem
   * @type {Array<string>}
   * @memberof DomainLocalDefinition
   */
  inventoryItems?: Array<string>;
  /**
   *
   * @type {Array<DomainObjective>}
   * @memberof DomainLocalDefinition
   */
  objectives?: Array<DomainObjective>;
  /**
   *
   * @type {string}
   * @memberof DomainLocalDefinition
   */
  remarks?: string;
  /**
   * Reference to identity.User
   * @type {Array<string>}
   * @memberof DomainLocalDefinition
   */
  users?: Array<string>;
}
