/* tslint:disable */
/* eslint-disable */
/**
 * Compliance Framework Configuration Service API
 * This is the API for the Compliance Framework Configuration Service.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DomainProperty
 */
export interface DomainProperty {
    /**
     * 
     * @type {string}
     * @memberof DomainProperty
     */
    _class?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainProperty
     */
    group?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainProperty
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainProperty
     */
    ns?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainProperty
     */
    remarks?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainProperty
     */
    value?: string;
}
