/* tslint:disable */
/* eslint-disable */
/**
 * Compliance Framework Configuration Service API
 * This is the API for the Compliance Framework Configuration Service.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DomainLink
 */
export interface DomainLink {
    /**
     * 
     * @type {string}
     * @memberof DomainLink
     */
    href?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainLink
     */
    mediaType?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainLink
     */
    rel?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainLink
     */
    resourceFragment?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainLink
     */
    text?: string;
}
