/* tslint:disable */
/* eslint-disable */
/**
 * Compliance Framework Configuration Service API
 * This is the API for the Compliance Framework Configuration Service.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DomainLink } from './domain-link';
import { DomainProperty } from './domain-property';
/**
 * 
 * @export
 * @interface DomainObjectiveSelection
 */
export interface DomainObjectiveSelection {
    /**
     * 
     * @type {string}
     * @memberof DomainObjectiveSelection
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DomainObjectiveSelection
     */
    exclude?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DomainObjectiveSelection
     */
    include?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof DomainObjectiveSelection
     */
    includeAll?: boolean;
    /**
     * 
     * @type {Array<DomainLink>}
     * @memberof DomainObjectiveSelection
     */
    links?: Array<DomainLink>;
    /**
     * 
     * @type {Array<DomainProperty>}
     * @memberof DomainObjectiveSelection
     */
    props?: Array<DomainProperty>;
    /**
     * 
     * @type {string}
     * @memberof DomainObjectiveSelection
     */
    remarks?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainObjectiveSelection
     */
    title?: string;
}
