/* tslint:disable */
/* eslint-disable */
/**
 * Compliance Framework Configuration Service API
 * This is the API for the Compliance Framework Configuration Service.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface HandlerAttachMetadataRequest
 */
export interface HandlerAttachMetadataRequest {
    /**
     * 
     * @type {string}
     * @memberof HandlerAttachMetadataRequest
     */
    collection: string;
    /**
     * 
     * @type {string}
     * @memberof HandlerAttachMetadataRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof HandlerAttachMetadataRequest
     */
    revisionDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlerAttachMetadataRequest
     */
    revisionRemarks?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlerAttachMetadataRequest
     */
    revisionTitle?: string;
}
