/* tslint:disable */
/* eslint-disable */
/**
 * Compliance Framework Configuration Service API
 * This is the API for the Compliance Framework Configuration Service.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HandlerCreateActivityRequestSubjectsExpressions } from './handler-create-activity-request-subjects-expressions';
/**
 * 
 * @export
 * @interface HandlerCreateActivityRequestSubjects
 */
export interface HandlerCreateActivityRequestSubjects {
    /**
     * 
     * @type {string}
     * @memberof HandlerCreateActivityRequestSubjects
     */
    description: string;
    /**
     * 
     * @type {Array<HandlerCreateActivityRequestSubjectsExpressions>}
     * @memberof HandlerCreateActivityRequestSubjects
     */
    expressions?: Array<HandlerCreateActivityRequestSubjectsExpressions>;
    /**
     * 
     * @type {Array<string>}
     * @memberof HandlerCreateActivityRequestSubjects
     */
    ids?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof HandlerCreateActivityRequestSubjects
     */
    labels?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof HandlerCreateActivityRequestSubjects
     */
    query?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlerCreateActivityRequestSubjects
     */
    title: string;
}
