/* tslint:disable */
/* eslint-disable */
/**
 * Compliance Framework Configuration Service API
 * This is the API for the Compliance Framework Configuration Service.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface HandlerCreateActivityRequestProvider
 */
export interface HandlerCreateActivityRequestProvider {
    /**
     * 
     * @type {string}
     * @memberof HandlerCreateActivityRequestProvider
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof HandlerCreateActivityRequestProvider
     */
    _package: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof HandlerCreateActivityRequestProvider
     */
    params?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof HandlerCreateActivityRequestProvider
     */
    version: string;
}
