/* tslint:disable */
/* eslint-disable */
/**
 * Compliance Framework Configuration Service API
 * This is the API for the Compliance Framework Configuration Service.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface HandlerCreateActivityRequestSubjectsExpressions
 */
export interface HandlerCreateActivityRequestSubjectsExpressions {
  /**
   *
   * @type {string}
   * @memberof HandlerCreateActivityRequestSubjectsExpressions
   */
  key?: string;
  /**
   *
   * @type {string}
   * @memberof HandlerCreateActivityRequestSubjectsExpressions
   */
  operator?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof HandlerCreateActivityRequestSubjectsExpressions
   */
  values?: Array<string>;
}
