/* tslint:disable */
/* eslint-disable */
/**
 * Compliance Framework Configuration Service API
 * This is the API for the Compliance Framework Configuration Service.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HandlerCreateCatalogRequestCatalog } from "./handler-create-catalog-request-catalog";
/**
 *
 * @export
 * @interface HandlerCreateCatalogRequest
 */
export interface HandlerCreateCatalogRequest {
  /**
   *
   * @type {HandlerCreateCatalogRequestCatalog}
   * @memberof HandlerCreateCatalogRequest
   */
  catalog?: HandlerCreateCatalogRequestCatalog;
}
