/* tslint:disable */
/* eslint-disable */
/**
 * Compliance Framework Configuration Service API
 * This is the API for the Compliance Framework Configuration Service.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HandlerCreateActivityRequestProvider } from './handler-create-activity-request-provider';
import { HandlerCreateActivityRequestSubjects } from './handler-create-activity-request-subjects';
/**
 * 
 * @export
 * @interface HandlerCreateActivityRequest
 */
export interface HandlerCreateActivityRequest {
    /**
     * 
     * @type {string}
     * @memberof HandlerCreateActivityRequest
     */
    description?: string;
    /**
     * 
     * @type {HandlerCreateActivityRequestProvider}
     * @memberof HandlerCreateActivityRequest
     */
    provider: HandlerCreateActivityRequestProvider;
    /**
     * 
     * @type {HandlerCreateActivityRequestSubjects}
     * @memberof HandlerCreateActivityRequest
     */
    subjects?: HandlerCreateActivityRequestSubjects;
    /**
     * 
     * @type {string}
     * @memberof HandlerCreateActivityRequest
     */
    title: string;
}
