/* tslint:disable */
/* eslint-disable */
/**
 * Compliance Framework Configuration Service API
 * This is the API for the Compliance Framework Configuration Service.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ApiError } from '../models';
import { HandlerAttachMetadataRequest } from '../models';
/**
 * MetadataApi - axios parameter creator
 * @export
 */
export const MetadataApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This method attaches metadata to a specific revision.
         * @summary Attaches metadata to a specific revision
         * @param {HandlerAttachMetadataRequest} body Revision that will be attached
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiMetadataRevisionsPost: async (body: HandlerAttachMetadataRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling apiMetadataRevisionsPost.');
            }
            const localVarPath = `/api/metadata/revisions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MetadataApi - functional programming interface
 * @export
 */
export const MetadataApiFp = function(configuration?: Configuration) {
    return {
        /**
         * This method attaches metadata to a specific revision.
         * @summary Attaches metadata to a specific revision
         * @param {HandlerAttachMetadataRequest} body Revision that will be attached
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetadataRevisionsPost(body: HandlerAttachMetadataRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<string>>> {
            const localVarAxiosArgs = await MetadataApiAxiosParamCreator(configuration).apiMetadataRevisionsPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MetadataApi - factory interface
 * @export
 */
export const MetadataApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * This method attaches metadata to a specific revision.
         * @summary Attaches metadata to a specific revision
         * @param {HandlerAttachMetadataRequest} body Revision that will be attached
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiMetadataRevisionsPost(body: HandlerAttachMetadataRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<string>> {
            return MetadataApiFp(configuration).apiMetadataRevisionsPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MetadataApi - object-oriented interface
 * @export
 * @class MetadataApi
 * @extends {BaseAPI}
 */
export class MetadataApi extends BaseAPI {
    /**
     * This method attaches metadata to a specific revision.
     * @summary Attaches metadata to a specific revision
     * @param {HandlerAttachMetadataRequest} body Revision that will be attached
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetadataApi
     */
    public async apiMetadataRevisionsPost(body: HandlerAttachMetadataRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<string>> {
        return MetadataApiFp(this.configuration).apiMetadataRevisionsPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
